# Generated by Django 2.1.4 on 2019-07-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名称')),
                ('app_name_cn', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名称')),
                ('app_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='应用类型')),
                ('git_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Git 地址')),
                ('git_properties', models.CharField(blank=True, max_length=100, null=True, verbose_name='配置文件')),
                ('java_version',
                 models.IntegerField(choices=[(1, 'version 1.6'), (2, 'version 1.7'), (3, 'version 1.8')], null=True,
                                     verbose_name='Java版本')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建者')),
            ],
            options={
                'permissions': (
                    ('view_appProject', '查看应用信息'), ('add_appProject', '添加应用'), ('change_appProject', '编辑应用'),
                    ('delete_appProject', '删除应用')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='平台名')),
                ('owner', models.CharField(max_length=64, null=True, verbose_name='负责人')),
                ('phone', models.CharField(max_length=64, null=True, verbose_name='手机号')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, verbose_name='描述')),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建者')),
            ],
            options={
                'permissions': (('view_platform', '查看平台'), ('add_platform', '添加平台'), ('change_platform', '编辑平台'),
                                ('delete_platform', '删除平台')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReleasePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='代码版本')),
                ('app_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='应用版本')),
                ('plan_status', models.NullBooleanField(default=False, verbose_name='发布状态')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                          related_name='apps', to='release.AppProject', verbose_name='发布应用')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建者')),
            ],
            options={
                'permissions': (
                    ('view_releasePlan', '查看发布计划'), ('add_releasePlan', '添加发布计划'), ('change_releasePlan', '编辑发布计划'),
                    ('delete_releasePlan', '删除发布计划')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='appproject',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='servers', to='release.Platform', verbose_name='所属平台'),
        ),
    ]
