# Generated by Django 2.1.4 on 2019-07-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('release', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='机房名称')),
                ('bandwidth', models.CharField(blank=True, max_length=32, verbose_name='带宽')),
                ('contact', models.CharField(blank=True, max_length=128, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='地址')),
                ('intranet', models.TextField(blank=True, verbose_name='内网')),
                ('extranet', models.TextField(blank=True, verbose_name='外网')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('operator', models.CharField(blank=True, max_length=32, verbose_name='运营商')),
                ('comment', models.TextField(blank=True, verbose_name='描述')),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建者')),
            ],
            options={
                'permissions': (
                    ('view_idc', '查看IDC'), ('add_idc', '添加IDC'), ('change_idc', '编辑IDC'), ('delete_idc', '删除IDC')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_ip', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='内网地址')),
                ('ex_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='外网地址')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目名称')),
                ('host_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名称')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务名称')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU型号')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU核数')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='CPU个数')),
                ('os_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='系统版本')),
                ('os_kernel', models.CharField(blank=True, max_length=100, null=True, verbose_name='系统内核')),
                ('status', models.NullBooleanField(default=False, verbose_name='运行状态')),
                ('max_open_files', models.IntegerField(blank=True, null=True, verbose_name='最大打开文件数')),
                ('uptime', models.IntegerField(blank=True, null=True, verbose_name='在线时间（天）')),
                ('mem', models.CharField(blank=True, max_length=100, null=True, verbose_name='内存')),
                ('mem_free', models.CharField(blank=True, max_length=100, null=True, verbose_name='剩余内存')),
                ('mem_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='内存使用率')),
                ('disk', models.CharField(blank=True, max_length=100, null=True, verbose_name='磁盘')),
                ('disk_free', models.CharField(blank=True, max_length=100, null=True, verbose_name='剩余磁盘')),
                ('disk_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='磁盘使用率')),
                ('swap_total', models.CharField(blank=True, max_length=100, null=True, verbose_name='总交换内存')),
                ('swap_free', models.CharField(blank=True, max_length=100, null=True, verbose_name='剩余交换内存')),
                ('swap_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='交换内存使用率')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('app_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='app', to='release.AppProject', verbose_name='部署应用')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建者')),
            ],
            options={
                'permissions': (
                    ('view_server', '查看主机列表'), ('add_server', '添加主机'), ('change_server', '编辑主机'),
                    ('update_server', '更新主机'),
                    ('delete_server', '删除主机'), ('view_monitor', '查看监控列表')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='资产组名')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, verbose_name='描述')),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建者')),
            ],
            options={
                'permissions': (
                    ('view_serverGroup', '查看资产组'), ('add_serverGroup', '添加资产组'), ('change_serverGroup', '编辑资产组'),
                    ('delete_serverGroup', '删除资产组')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名称')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='登陆用户')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='登陆密码')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注信息')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'permissions': {('add_systemUser', '新增登陆用户'), ('delete_systemUser', '删除登陆用户'),
                                ('view_systemUser', '只读系统登陆用户'), ('change_systemUser', '编辑登陆用户')},
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='servers', to='cmdb.ServerGroup', verbose_name='资产组'),
        ),
        migrations.AddField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='servers', to='cmdb.Idc', verbose_name='IDC 机房'),
        ),
        migrations.AddField(
            model_name='server',
            name='system_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='cmdb.SystemUser', verbose_name='登陆用户'),
        ),
    ]
