# Generated by Django 2.1.4 on 2019-07-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KubeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(
                    choices=[(0, 'deploy'), (1, 'etcd'), (2, 'kube-master'), (3, 'kube-node'), (4, 'lb')],
                    verbose_name='节点角色')),
                ('LB_ROLE',
                 models.IntegerField(choices=[(0, '非lb角色选此项'), (1, 'master'), (2, 'backup')], verbose_name='节点类型')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建者')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                         to='cmdb.Server', verbose_name='节点IP')),
            ],
            options={
                'permissions': (
                    ('view_kubeNode', '查看K8S节点'), ('add_kubeNode', '添加K8S节点'), ('change_kubeNode', '编辑K8S节点'),
                    ('delete_kubeNode', '删除K8S节点')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KubeVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HARBOR_DOMAIN', models.CharField(blank=True, max_length=64, null=True, verbose_name='harbor域名')),
                ('NTP_ENABLED',
                 models.CharField(blank=True, default='no', max_length=64, null=True, verbose_name='是否时间同步')),
                ('NEW_INSTALL',
                 models.CharField(blank=True, default='no', max_length=64, null=True, verbose_name='是否新建')),
                ('EX_VIP', models.CharField(blank=True, max_length=64, null=True, verbose_name='外部负载均衡')),
                ('DEPLOY_MODE', models.CharField(blank=True, max_length=64, verbose_name='集群部署模式')),
                ('K8S_VER', models.CharField(blank=True, max_length=64, verbose_name='集群主版本号')),
                ('MASTER_IP', models.CharField(blank=True, max_length=64, verbose_name='LB节点VIP')),
                ('KUBE_APISERVER', models.CharField(blank=True, max_length=64, verbose_name='APISERVER')),
                ('CLUSTER_NETWORK', models.CharField(blank=True, max_length=64, verbose_name='集群网络插件')),
                ('SERVICE_CIDR', models.CharField(blank=True, max_length=64, verbose_name='服务网段')),
                ('CLUSTER_CIDR', models.CharField(blank=True, max_length=64, verbose_name='POD网段')),
                ('NODE_PORT_RANGE', models.CharField(blank=True, max_length=64, verbose_name='服务端口范围')),
                ('CLUSTER_KUBERNETES_SVC_IP',
                 models.CharField(blank=True, max_length=64, verbose_name='kubernetes服务IP')),
                ('CLUSTER_DNS_SVC_IP', models.CharField(blank=True, max_length=64, verbose_name='集群DNS服务IP')),
                ('CLUSTER_DNS_DOMAIN', models.CharField(blank=True, max_length=64, verbose_name='集群DNS域名')),
                ('BASIC_AUTH_USER', models.CharField(blank=True, max_length=64, verbose_name='集群BasicAuth用户名')),
                ('BASIC_AUTH_PASS', models.CharField(blank=True, max_length=64, verbose_name='集群BasicAuth密码')),
                ('bin_dir', models.CharField(blank=True, max_length=64, verbose_name='二进制文件目录')),
                ('ca_dir', models.CharField(blank=True, max_length=64, verbose_name='证书目录')),
                ('base_dir', models.CharField(blank=True, max_length=64, verbose_name='部署目录')),
            ],
            options={
                'permissions': (('view_kubeCluster', '查看K8S集群参数模板'), ('add_kubeCluster', '添加K8S集群参数模板'),
                                ('change_kubeCluster', '编辑K8S集群参数模板'), ('delete_kubeCluster', '删除K8S集群参数模板')),
                'default_permissions': (),
            },
        ),
    ]
